name: Docker Build and Deployment

on:
  push:
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CD Environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Build bundle
      run: make bundle BUNDLE_RUNTIMES=false

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: yetanalytics/persephone

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
